### ISSUE TITLE
Can you fix this error

### ISSUE THREAD

**Issue by leroyvaughan** [KhafraDev/4lyrics#2]
**I'm using VSCode and installed  your module this way:**  'npm install 4lyrics'

**am getting this in my app:**

Could not find a declaration file for module '4lyrics'. 'c:/z_storage/projects/REACT/node-react-boilerplate/node_modules/4lyrics/index.js' implicitly has an 'any' type.
  Try `npm install @types/4lyrics` if it exists or add a new declaration (.d.ts) file containing `declare module '4lyrics';`ts(7016)

Can you fix this? Or have any idea how to fix without me having to modify your module?

**Comment by KhafraDev** [comment]
Are you using TypeScript?

I was looking to just do a complete re-haul of the project because I am dissatisfied with it and will try adding typings in that re-write.
